version: "3"

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  evmos-devnet1:
    image: evmos-devnet1
    build:
      context: ./evmos-devnet
      args:
        - commit_hash=31fd2a830a0d1812b2c54a323dc85d1a7ec5092e
    restart: always
    ports:
      - 8545:8545
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:26657/status" ]
      interval: 30s
      timeout: 10s
      retries: 5

  evmos-devnet2:
    image: evmos-devnet2
    build:
      context: ./evmos-devnet
      args:
        - commit_hash=343ff54bb593299032d903feb6416e23d024eb48
    restart: always
    ports:
      - 8645:8545
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:26657/status" ]
      interval: 30s
      timeout: 10s
      retries: 5

  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 8000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always

  tx-bot1:
    image: vhomsi/tx-bot
    ports:
      - 8081:8080
    depends_on:
      - evmos-devnet1
    environment:
      - ORCH_PRIV_KEY=0x1c384b3fb9a1cff8caee1e2d078bb9bc28a542dcc7ac779a445dc68b3dc2fe1f
      - RPC_URL=http://evmos-devnet1:8545
    restart: always

  tx-bot2:
    image: vhomsi/tx-bot
    ports:
      - 8082:8080
    depends_on:
      - evmos-devnet2
    environment:
      - ORCH_PRIV_KEY=0x1c384b3fb9a1cff8caee1e2d078bb9bc28a542dcc7ac779a445dc68b3dc2fe1f
      - RPC_URL=http://evmos-devnet2:8545
    restart: always

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.45.0
    container_name: cadvisor
    ports:
      - 8090:8080
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
    privileged: true
    restart: always
    deploy:
      mode: global